name: vpn
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  equatable: ^2.0.5
  dio: ^5.3.0
  get_it: ^7.2.0
  #
  figma_squircle: ^0.5.3
  lottie: ^2.4.0
  #
  url_launcher: ^6.1.12
  device_info_plus: ^9.0.3
  #
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0
  #

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: fonts/SpaceGrotesk-Bold.ttf
          weight: 900
        - asset: fonts/SpaceGrotesk-SemiBold.ttf
          weight: 700
        - asset: fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: fonts/SpaceGrotesk-Regular.ttf
          weight: 300
        - asset: fonts/SpaceGrotesk-Light.ttf
          weight: 100

    - family: Alatsi
      fonts:
        - asset: fonts/Alatsi-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
